version: '3'
services:
  frontend:
    build:
      context: ./Angular\wikidata-panel
    ports:
      - "8080:80"

  backend:
    build:
      context: ./Python
    ports:
      - "8888:8888"
    depends_on:
      - frontend  

    links:
      - frontend 
